// Datos del panel. Claude actualiza este fichero cuando le cuentas novedades.
// Plan de 31 días: todo uso real, una sola cuenta, sin automatizar, sin compras cruzadas.
window.DATA = {
  account: { alias: "Mi cuenta Vinted", createdAt: null }, // createdAt: "2026-10-07"
  plan: [
    { d:1, min:20, title:"Crear la cuenta",
      steps:["Usa tu móvil de siempre y tu wifi o datos habituales. No uses VPN.","Instala la app oficial de Vinted y regístrate con un email real que uses a diario y una contraseña que no uses en otro sitio.","Confirma el email desde el enlace que te llega.","Pon tu nombre real o un alias coherente (no uno aleatorio).","Cierra la app. No publiques ni compres nada hoy."],
      dont:"No uses emails temporales ni crees más de una cuenta." },
    { d:2, min:15, title:"Perfil: foto, descripción y ubicación",
      steps:["Foto de perfil tuya, nítida y con buena luz. Sin logos ni fotos de internet.","Descripción corta y natural, por ejemplo: «Vendo ropa y zapatillas que ya no uso. Envío rápido y trato cuidado.»","Ubicación real (ciudad o provincia).","Revisa que el idioma de la app sea el tuyo."],
      dont:"No pongas enlaces, redes sociales ni teléfono en la descripción." },
    { d:3, min:15, title:"Envío y cobro",
      steps:["Añade tu dirección de envío real.","Configura el método de cobro a tu nombre (Vinted Pay).","Comprueba que los datos coinciden con tu identidad."],
      dont:"No uses datos bancarios ni direcciones de otra persona." },
    { d:4, min:20, title:"Verificación y ajustes",
      steps:["Si Vinted te ofrece verificar la identidad, hazlo con tu documento real.","Revisa los ajustes de notificaciones para enterarte rápido de mensajes y ofertas.","Navega 5 minutos por anuncios de zapatillas y ropa sin hacer nada más."],
      dont:"No ofertes ni compres todavía." },
    { d:5, min:10, title:"Navegar con intención real",
      steps:["Busca 3 cosas que te interesen de verdad (una prenda, unas zapatillas, un accesorio).","Mira los anuncios y los perfiles de los vendedores.","Guarda 3-5 favoritos solo si te gustan de verdad."],
      dont:"No des likes en masa, no sigas a muchas cuentas y no compres." },
    { d:6, min:3, title:"Día de descanso",
      steps:["Abre la app 2 o 3 minutos y mira las notificaciones.","Cierra."],
      dont:"Nada más. Descansar también es parte del ritmo." },
    { d:7, min:40, title:"Preparar los artículos de casa",
      steps:["Haz una lista de unos 10 artículos de casa que de verdad quieras vender (ropa, accesorios, objetos).","Elige los 2 primeros y haz fotos propias: luz natural, fondo neutro, 4-6 fotos (frente, detalle, etiqueta, posibles defectos).","Anota para cada uno: marca, talla o medidas, estado, motivo de venta y precio de compra aproximado.","Apúntalo en la hoja de seguimiento."],
      dont:"No uses fotos de internet ni fotos que no sean tuyas." },
    { d:8, min:25, title:"Descripciones y precios",
      steps:["Redacta las descripciones de los 2 primeros: marca, tipo de prenda, talla, color, estado, medidas y motivo de venta, en 3-5 líneas.","Mira 5 anuncios vendidos o parecidos para fijar un precio realista. Evita precios muy bajos o muy altos.","Haz las fotos de los 2 siguientes artículos."],
      dont:"No subas nada hoy." },
    { d:9, min:20, title:"Subir el artículo 1",
      steps:["Sube las fotos y escribe el título con el formato marca + tipo + talla + color.","Elige la categoría correcta, el estado real y el tamaño de paquete.","Pon la descripción y el precio, revisa la vista previa y publica.","Cierra la app."],
      dont:"No subas otro artículo hoy." },
    { d:10, min:10, title:"Entrar y responder",
      steps:["Abre la app, responde mensajes u ofertas con educación (en menos de 2 horas si puedes).","Navega 3-5 minutos y guarda 1 o 2 favoritos reales."],
      dont:"No bajes el precio todavía." },
    { d:11, min:5, title:"Día de descanso",
      steps:["Mira solo las notificaciones y responde si hay mensajes."],
      dont:"No subas ni compres." },
    { d:12, min:20, title:"Subir el artículo 2",
      steps:["Mismo proceso que el día 9: fotos propias, título, categoría, estado, descripción y precio.","Revisa la vista previa y publica."],
      dont:"No subas más de un artículo hoy." },
    { d:13, min:10, title:"Entrar y responder",
      steps:["Responde mensajes y ofertas.","Navega unos minutos y guarda algún favorito si te interesa."],
      dont:"No hagas ofertas por hacer." },
    { d:14, min:15, title:"Revisión semanal 2",
      steps:["Cuéntame cuántos mensajes, ofertas o visitas has tenido.","Mejora fotos o descripción del artículo con menos interés.","Anota todo en el panel."],
      dont:"No bajes el precio aún." },
    { d:15, min:20, title:"Subir el artículo 3",
      steps:["Mismo proceso: fotos propias, título, categoría, estado, descripción y precio.","Publica y cierra."],
      dont:"No subas más de uno." },
    { d:16, min:20, title:"Primera compra real",
      steps:["Elige algo que necesites de verdad y que cueste poco (5-15 €).","Elige un vendedor con buenas valoraciones.","Escribe un mensaje educado y paga con Vinted Pay, sin sacar la conversación fuera de la app."],
      dont:"No compres a amigos ni a cuentas vinculadas a ti." },
    { d:17, min:10, title:"Entrar y gestionar",
      steps:["Responde mensajes. Si vendiste algo, prepara el envío.","Navega 3-5 minutos."],
      dont:"No subas nada hoy." },
    { d:18, min:20, title:"Subir el artículo 4",
      steps:["Fotos propias, título, categoría, estado, descripción y precio.","Publica y cierra."],
      dont:"Uno solo." },
    { d:19, min:10, title:"Recepción y primera valoración",
      steps:["Si llegó tu compra, confirma la recepción y valora al vendedor con honestidad.","Responde mensajes."],
      dont:"No valores antes de recibirlo." },
    { d:20, min:20, title:"Subir el artículo 5",
      steps:["Fotos propias, título, categoría, estado, descripción y precio.","Publica y cierra."],
      dont:"Uno solo." },
    { d:21, min:20, title:"Revisión semanal 3",
      steps:["Cuéntame cuántos artículos tienes, mensajes, ventas y valoraciones.","Si algún artículo lleva 2 semanas sin interés, bájale un 5-10 %.","Mira el índice de confianza del panel."],
      dont:"No subas nada nuevo hoy." },
    { d:22, min:20, title:"Subir el artículo 6",
      steps:["Fotos propias, título, categoría, estado, descripción y precio.","Publica y cierra."],
      dont:"Uno solo." },
    { d:23, min:15, title:"Envíos y valoraciones",
      steps:["Envía en 24-48h lo que hayas vendido y avisa al comprador.","Cuando lo reciba, pídele la valoración con un mensaje breve y educado.","Responde mensajes."],
      dont:"No presiones al comprador." },
    { d:24, min:20, title:"Subir el artículo 7",
      steps:["Fotos propias, título, categoría, estado, descripción y precio.","Publica y cierra."],
      dont:"Uno solo." },
    { d:25, min:5, title:"Día de descanso",
      steps:["Solo notificaciones y mensajes."],
      dont:"No subas ni compres." },
    { d:26, min:20, title:"Subir el artículo 8",
      steps:["Fotos propias, título, categoría, estado, descripción y precio.","Publica y cierra."],
      dont:"Uno solo." },
    { d:27, min:20, title:"Segunda compra o gestión de ventas",
      steps:["Si necesitas algo, haz otra compra real de poco importe.","Si vendiste algo, gestiona el envío y pide la valoración.","Responde mensajes."],
      dont:"No fuerces compras que no necesitas." },
    { d:28, min:30, title:"Subir el artículo 9 y revisión 4",
      steps:["Sube el artículo 9 con el mismo proceso.","Cuéntame los números: artículos, ventas, compras, valoraciones, avisos y revisiones.","Yo recalculo el índice y te digo cómo vas."],
      dont:"No subas zapatillas todavía." },
    { d:29, min:45, title:"Preparar las zapatillas (sin subir)",
      steps:["Haz 8-12 fotos propias de cada par: laterales, frontal, talón, lengüeta, plantilla, suela, costuras, etiqueta interior con el código de artículo y la caja con su etiqueta.","Guarda la prueba de compra de cada par, aunque sea una captura del pedido.","Apunta modelo exacto, colorway, talla y estado."],
      dont:"No subas nada todavía." },
    { d:30, min:30, title:"Descripción y precio",
      steps:["Redacta la descripción: marca, modelo exacto, colorway, talla y estado, en español y, si vendes en Francia, en francés.","Mira los vendidos reales de ese modelo para fijar el precio. No te pases por debajo de lo normal.","Decide con qué par empiezas."],
      dont:"No uses frases como «alternativa perfecta a…» ni compares con otros modelos." },
    { d:31, min:20, title:"Decidir el primer par",
      steps:["Mira el indicador «Listo para Samba» del panel.","Si está en verde, sube un solo par con tus fotos y la descripción. No subas otro hasta que se resuelva o se venda.","Si no está en verde, sigue 3 días más con uso normal y repite esta revisión.","Si entra en revisión, aporta lo que pidan sin re-subirlo."],
      dont:"No subas varios pares ni borres y re-subas el anuncio." }
  ],
  checklist: [
    { w: 1, t: "Crear cuenta con email y teléfono reales", done: false },
    { w: 1, t: "Foto de perfil y descripción corta", done: false },
    { w: 1, t: "Ubicación y dirección", done: false },
    { w: 1, t: "Método de cobro configurado", done: false },
    { w: 1, t: "Verificación de identidad (si la ofrece)", done: false },
    { w: 1, t: "Entrar 2-3 días unos minutos y navegar", done: false },
    { w: 2, t: "Entrar varios días y guardar favoritos de lo que me interese", done: false },
    { w: 2, t: "Subir 2 artículos de casa con fotos propias", done: false },
    { w: 2, t: "Responder mensajes en pocas horas", done: false },
    { w: 3, t: "Subir 3 artículos de casa más", done: false },
    { w: 3, t: "Hacer 1 compra real que necesite y valorarla", done: false },
    { w: 3, t: "Enviar en 24-48h si vendo algo y pedir valoración", done: false },
    { w: 4, t: "Llegar a ~10 artículos de casa publicados", done: false },
    { w: 4, t: "Seguir con compras y ventas reales", done: false },
    { w: 4, t: "Preparar fotos de las zapatillas (etiqueta, código, plantilla, suela, caja)", done: false },
    { w: 4, t: "Guardar prueba de compra de cada par", done: false },
    { w: 4, t: "Redactar descripción con modelo exacto, colorway y talla", done: false },
    { w: 4, t: "Fijar precio según vendidos reales", done: false },
    { w: 5, t: "Subir zapatillas de 1 en 1 o de 2 en 2", done: false },
    { w: 5, t: "Si entra en revisión, aportar lo que pidan y no re-subir en bucle", done: false }
  ],
  // estado: activo | revision | vendido | rechazado
  listings: [
    // { fecha:"2026-10-20", articulo:"Samba OG", modelo:"Blanco 42", coste:60, precio:90, estado:"activo", prueba:"captura pedido", motivo:"", precioVenta:null, comisionEnvio:null, valoracion:null, notas:"" }
  ],
  activity: [
    // { fecha:"2026-10-07", minutos:10, subidos:0, ventas:0, compras:0, valoraciones:0, avisos:0, notas:"" }
  ],
  ratings: [
    // { fecha:"2026-10-25", estrellas:5, comentario:"" }
  ]
};
